# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: 我的一点点
description: 思考一点点，写下一点点，就会多一点点
author:
  name: xuzou
  email: zjzouxu@gmail.com
  github: august-zou
  twitter: augustzou
  pinterest: 
  linkedin: 
  weibo: xuzou
  bio: 思考一点点，写下一点点，就会多一点点!
  email_md5: 58155757e0bb79f6bb85f28854a5c3b0

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

BASE_PATH: http://www.xuzou.me
